### ISSUE TITLE
Data structures and algorithms offline club/course

### ISSUE THREAD

**Issue by Sestri4kina** [kottans/kottans-ongoing-projects#13]
This issue is about 
+ [x] Course (if there are mentors who are willing to teach the subject)
+ [ ] Event
+ [ ] Project
+ [x] Other: Study club

By/for
+ [x] kottans
+ [x] non-kottans

Subject: Data structures and algorithms (preferably in Python) offline club/course

Term/duration: unknown

Keywords: offline, Kyiv, Python (or Java)

What do we need to reach the goal:

- decide on a source of learning (book, online course)
- decide on a format of learning depending on whether it's a course with mentors or a study club (if it's a study club, then just discussing the chapters of the chosen book or a better option is that at every meeting a different person can present the current subject at hand)
- decide on where to meet and how often

**Comment by kaflan** [comment]
Я бы походил

**Comment by fomenkosmart** [comment]
Interested in using Python for ML and BD

**Comment by sudodoki** [comment]
@Sestri4kina is there any other conversation happening elsewhere? Otherwise might suggest doing 
1) limiting choice to either [Cormen](https://mitpress.mit.edu/books/introduction-algorithms) or [Skiena](https://www.amazon.com/Algorithm-Design-Manual-Steven-Skiena/dp/1848000693) so it's subset of 'choose the book' problem 
2) if you go with the study group, be prepared to have 80% of people 'falling off' at one point or another
3) regarding place - use either some coworking place that's close to everyone involved or discuss free space with one of the companies (can try to send few contacts your way).
Another way to get more eyes on this is probably posting on DOU.
I would suggest creating simple form to capture people emails in case they are interested in either teaching or learning and their, like, algo knowledge level, so you could decide what to do next.

**Comment by programulya** [comment]
Cooool! How about https://www.amazon.com/Algorithms-4th-Robert-Sedgewick/dp/032157351X?

**Comment by Quodnon** [comment]
- [Poll](https://goo.gl/forms/wt1n70pGJNqAXckl2) created for gathering info. Access is given to OP @sudodoki  and @suchov 
- +1 👍  for Skiena: lots of exercises

**Comment by AntonLebiodkin** [comment]
Great idea! Once a week with study groups (possibly teams, which present each chapter) will be good.

**Comment by Komachka** [comment]
Sounds great! I would like to)

**Comment by Quodnon** [comment]
The poll will be opened for **2 more days**.
Currently 8 of 11 people interested in MOOC. Nobody wants Skiena 🐳 
As for  MOOC, there are 2 **[oss courses](https://github.com/ossu/computer-science#core-theory)** regarding algorithms. 

===
📆 Suitable time to kick-off for *me*: end of January 2018. After holidays
🕐 **Waiting**: poll  close
🚶 🚶‍♀️ **Next step**: deside on format.  @AMashoshyna 
❗️ **Help wanted**: create algorithm club repo for discussion and preparation @sudodoki @suchov

**Comment by Quodnon** [comment]
join discussion about organizing course in [telegram](https://t.me/joinchat/C1v8eg9udVHwnHbha8fYIQ)

**Comment by suchov** [comment]
@AMashoshyna @Quodnon  https://github.com/kottans/algorithm_club

**Comment by suchov** [comment]
@sudodoki @AMashoshyna is an owners of the repo
